export const FETCHING_COIN_DATA_START = 'FETCHING_COIN_DATA_START';
export const FETCHING_COIN_DATA_SUCCESS = 'FETCHING_COIN_DATA_SUCCESS';
export const FETCHING_COIN_DATA_FAIL = 'FETCHING_COIN_DATA_FAIL';